name: npm-publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - run: echo "//registry.npmjs.org/:_authToken=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" > .npmrc
      - run: npm ci
      - run: npm version "1.0.`date '+%Y%m%d%H%M%S'`" -m "Update version number to %s"
      - run: npm publish
